// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysparam.proto

package types // import "github.com/aergoio/aergo/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SysParam struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Mut                  bool     `protobuf:"varint,4,opt,name=mut" json:"mut,omitempty"`
	Dao                  bool     `protobuf:"varint,5,opt,name=dao" json:"dao,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysParam) Reset()         { *m = SysParam{} }
func (m *SysParam) String() string { return proto.CompactTextString(m) }
func (*SysParam) ProtoMessage()    {}
func (*SysParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_sysparam_f2d054d9e8e7269f, []int{0}
}
func (m *SysParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysParam.Unmarshal(m, b)
}
func (m *SysParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysParam.Marshal(b, m, deterministic)
}
func (dst *SysParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysParam.Merge(dst, src)
}
func (m *SysParam) XXX_Size() int {
	return xxx_messageInfo_SysParam.Size(m)
}
func (m *SysParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SysParam.DiscardUnknown(m)
}

var xxx_messageInfo_SysParam proto.InternalMessageInfo

func (m *SysParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SysParam) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *SysParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SysParam) GetMut() bool {
	if m != nil {
		return m.Mut
	}
	return false
}

func (m *SysParam) GetDao() bool {
	if m != nil {
		return m.Dao
	}
	return false
}

func init() {
	proto.RegisterType((*SysParam)(nil), "types.SysParam")
}

func init() { proto.RegisterFile("sysparam.proto", fileDescriptor_sysparam_f2d054d9e8e7269f) }

var fileDescriptor_sysparam_f2d054d9e8e7269f = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xae, 0x2c, 0x2e,
	0x48, 0x2c, 0x4a, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48,
	0x2d, 0x56, 0xca, 0xe1, 0xe2, 0x08, 0xae, 0x2c, 0x0e, 0x00, 0x49, 0x08, 0x09, 0x71, 0xb1, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0x94, 0xd4,
	0xe2, 0x64, 0x09, 0x26, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a,
	0x2a, 0xc1, 0x0c, 0x16, 0x84, 0x70, 0x84, 0x04, 0xb8, 0x98, 0x73, 0x4b, 0x4b, 0x24, 0x58, 0x14,
	0x18, 0x35, 0x38, 0x82, 0x40, 0x4c, 0x90, 0x48, 0x4a, 0x62, 0xbe, 0x04, 0x2b, 0x44, 0x24, 0x25,
	0x31, 0xdf, 0x49, 0x21, 0x4a, 0x2e, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57,
	0x3f, 0x31, 0xb5, 0x28, 0x3d, 0x3f, 0x33, 0x1f, 0x42, 0xeb, 0x83, 0xdd, 0x93, 0xc4, 0x06, 0x76,
	0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x38, 0xfa, 0xe2, 0x24, 0xaf, 0x00, 0x00, 0x00,
}
