// Code generated by "stringer -type=PenaltyCategory"; DO NOT EDIT.

package audit

import "strconv"

const _PenaltyCategory_name = "ShortTermLongTermPermanent"

var _PenaltyCategory_index = [...]uint8{0, 9, 17, 26}

func (i PenaltyCategory) String() string {
	if i < 0 || i >= PenaltyCategory(len(_PenaltyCategory_index)-1) {
		return "PenaltyCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PenaltyCategory_name[_PenaltyCategory_index[i]:_PenaltyCategory_index[i+1]]
}
